--- #YAML:1.0
name:               Queue-Q
version:            0.19
abstract:           Mix-and-match Queue Implementations and Backends
author:
    - Steffen Mueller <smueller@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                0
    Class::XSAccessor:   0.12
    constant:            0
    Digest::SHA1:        0
    File::Slurp:         0
    File::Spec:          0
    JSON::XS:            0
    List::Util:          0
    parent:              0
    Redis:               1.955
    Redis::ScriptCache:  0.01
    Scalar::Util:        0
    Sereal::Decoder:     0.10
    Sereal::Encoder:     0.10
    Test::More:          0.88
    Time::HiRes:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
